# name: Portpro-Infra-Provision-dev

# on:
#   push:
#     branches:
#       - dev

# permissions:
#   contents: read

# env:
#   awsRegion: "us-east-1"

# jobs:
#   infra-deploy-dev:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v3
        
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v3
#         with:
#             aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#             aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#             aws-region: ${{ env.awsRegion }}
#             # role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
#             role-session-name: OIDCSession
            
#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: '1.3.10'

#       - name: Verify Terraform version
#         run: terraform --version

#       - name: Terraform Initialize
#         run: terraform init -reconfigure

#       - name: Terraform workspace
#         run: terraform workspace select dev

#       - name: Terraform validation
#         run: terraform validate

#       - name: Terraform plan
#         run: terraform plan -lock=false
